apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: bazarr
  namespace: media
spec:
  parentRefs:
    - name: agentgateway
      namespace: kgateway-system
  hostnames:
    - bazarr.tmdev.pl
  rules:
    - backendRefs:
        - name: servarr-bazarr
          port: 6767
          namespace: media