apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  parentRefs:
    - name: agentgateway
      namespace: kgateway-system
  hostnames:
    - jellyfin.tmdev.pl
  rules:
    - backendRefs:
        - name: servarr-jellyfin
          port: 8096
          namespace: media