apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  parentRefs:
    - name: agentgateway
      namespace: kgateway-system
  hostnames:
    - longhorn.tmdev.pl
  rules:
    - backendRefs:
        - name: longhorn-frontend
          port: 80
          namespace: longhorn-system