apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  parentRefs:
    - name: agentgateway
      namespace: kgateway-system
  hostnames:
    - prowlarr.tmdev.pl
  rules:
    - backendRefs:
        - name: servarr-prowlarr
          port: 9696
          namespace: media