apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: media
spec:
  parentRefs:
    - name: agentgateway
      namespace: kgateway-system
  hostnames:
    - torrent.tmdev.pl
  rules:
    - backendRefs:
        - name: qbittorrent
          port: 8080
          namespace: media