apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: radarr
  namespace: media
spec:
  parentRefs:
    - name: agentgateway
      namespace: kgateway-system
  hostnames:
    - radarr.tmdev.pl
  rules:
    - backendRefs:
        - name: servarr-radarr
          port: 7878
          namespace: media