apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: sonarr
  namespace: media
spec:
  parentRefs:
    - name: agentgateway
      namespace: kgateway-system
  hostnames:
    - sonarr.tmdev.pl
  rules:
    - backendRefs:
        - name: sonarr
          port: 8989
          namespace: media