apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/tmusial99/haku-infra.git
        revision: master
        directories:
          - path: apps/*/*
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        env: '{{ .path.path | dir | base }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tmusial99/haku-infra.git
        targetRevision: master
        path: '{{ .path.path }}'
        kustomize:
          enableHelm: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.path | dir | base }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
