---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAq6nQ6i9M3mBrLhcivi7WNLXwT40SpRmfYKHj088y8izM4pkBSk7Ywy0F7Eub+rhgiagQoqO/X7/ZzSbkkd98vKSMAulEEAuwKyGmtBs6q80xF+zE+qe685HZi9ifnQDZUy3IUZbGs4g1VbRkIHP4nzeI3BcCnRTKs+dZSNk2u44FPYefEJoFmNdp5j0vPp4a1sg0PXQOR+22Z34yXCFF/CRW3Piccm6JJHR0W1Cq8TI7UFn+SklmR082fmyO54XfJK3YZsjM3NJsZaKSBJjHIsNTA8Ka3dGbnlpTWD41FKgaQiL4T47Km5Vng6IynY37dHNXhl7DzVoqGZ1Z02pE8W4aR4n+Wa3DEResWkQMMI396j5rADFiBDWDRHcClZU7cHotVUgs3SD0SYGP9UXKEeTdMM/KaIbg5l2V+JHPoDI5buiHzVm41gxb2YdVt4HMiSkQGNAfuEn1n0YWbRwmHI1DdCGgE3LvOXNNlz4JfHJkljaM48sBp9n23hQcf2mLGbcttQhq/jHjT3J2Ct/mNKouvecLq9SO0xKMgioUYZdwiErV0+1/5VEPZmE9c6Dah27SNHxWYVDAY86sXyDM2DW5CmHfnLwJ0KDIT6HTtsFs1ESywtDZ16CoYmHnCPLAvOFE15Wo2enD/1EpzmHr82OgjIIJiqzZ9RATGtA+jPg+Fd/4L7HLN/rctSkbRXCzLY1H+UP9kkUMKDTbjWIKlYlZsfvn2FDktgQ5y+UUIpkvhpUGU+lLS
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
