---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAkdvvfRwSYe8l+MUydM/PPOyhJvyDGHMbqEqazewZEmKZ73mBIHd76KfdDmHwF4v7MKz1m2+v77ezJ/KfPY8qro7FBpiHyYer95+Dfox6n/68vLPtfVp6K846yK3yt59IQcczygrboytp4djkIpsvoeVHBUszAAS2B4Q0PY3gBzMP5UwjwEZ/3beKnB8eR6RvcMbjXTybNCdPhFd3HROOoJuPLGdM+lxNy7zNeKGKYbAzjgJAcf9QDYtQ5RkDZxA0SLHr0Qkck2XLyEqZPK2mB9pywLyqKysqw8I+X0shBedhpObEEjf679rqM90JSUganuTSAgdGbovmg8IGwq7IyodK+had6CTMLsQR0wzV94pKD9/07bCVVyNFfvDlN9ov56R4V/I/VanXu5WWFUjCR9lYMV1tJrqKZQfmXQ0MDClVBezQjVMNtZT7mnNiZb2UvKsvoa4ArclcfqDko75OLRnE9evt4yh6cPnmBcrPg+dEnTXBZ4ekcK7Lg37qa1Dqcfex7BkwmD+1IFM3OO/gbyRf6T/aHceYr4kV6w2PXs+PzLVymnVrPdEHD6SEH8vA0BkckfZJwnS8rZUXs27v3MuBY9tMWcpIZMtOFtvJsGxwxNAUSJpRxapLtMdiiFG7uS4dBJzHPJKUedZqI0EjiV//aR4MfGtura8nN3ej0W0tqTYkvW6RSGiSDBXvbjsCaN8nuoZrTk4Be7JhTdn7yXuQFDesVWbQD2VLIFJr1ikkjgAd0pmfS
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
