---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCP4MsQ2gPRiPSRhBEX9yXVqiL/0KUO68HUlBfUW6r43h++GI+wwMV3lV+zSiscltgT03Ec8kEtQlc6vqmapD8mckI4g5lBa5aHmoGCvA4BFN5nMIj7n/jbHryh1dBS+ukcNTpRFn6SHSOiqY908fhPPQMNUX6t0xEMGGwky7BmiHxpNKskkqkzyDtbRn1+KAKTG9+QGTx5VYiuOio3PNlZ1UouudE/TKc5OuoKY0xK178YVW2gvFfNPS9mC028SiNMHiL5Ia+yCP+LT9Gi20NcSsu0W2tUkwOWkqvwmJ0fPytQPbcOpYOQ7zQsHt1IYKS8XlDXsJ2Yj4+VdQL4k71dnDWbXq3xXU9PURBlg28voIHkChluLA7CX22/qbq5nzXFHxPXq267CLVPcFIF/EfMdJPdjy1E4LLLWCoi75WhHSyQ9nOjdpFkY0C98l+YPYx1/v2lL561pnjdMtGhzAhxgtOH/oKYuEc1n/sMQPaU5uAvauTr3mNxlrNzk2kocFiWKzL5+SjWbZ9CWdjn5V+NfIXyB97EI5qIW2n4tWTOuoqmGUgpA2ZJEidIkJJEev6Q4Qn212HBhZLLVVLegYJoHTGBt3oOiswpPRaVkTJ9prmy4DDzBLJC7XwncJVSA7LKo6vLYybU0TLddcn939jye+pJXZjpny3QjXJFQIN3gYfzSEJrcNbWaO4sR48NwjhZrxeMdEyuq8XHQAQ1ts+KXUThVYnx0gTTYSo3nmZm+KeOpg4rT0QgjAzhFVRbAj3Id2dOH6/LDlzbTSF6eS7GSgBeEhKhq21+LJPITsziUHbSGb0ZxDCgViEWeegE3N7PH6th1UnD0fO5joHI57BNIN7sq+41vP5HjDet56qtPoAn6vldDB1MdqeN97J/u0kJIdIVUeM7KBoWciRlB9iqHbjoK8sWiFwcPpO5MQbBC8MT
  template:
    metadata:
      name: ghcr-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
