---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBzEcrfo9WDQhimcu9T/5YIMdanqGtiAlJBELz1s4V9LulmsTnJ3Od3gKdgKRH3/iMtNa1K0B3Xsl10FE++gYptpcciGigp5UZY1cjo/W9V1abzEbTLX6M1YXOMJhz3n7nHxXf0cOAycAY6D9tQXxoVxKFQNlbqEi/m7SdUNmS2fXpPGgb5R1/u4i5ngEmPw1Jgh1KO+lkgTPa/aFqXE+IBXnFyJDD5DMhiN9w7V5lnsERQampFZWKOYvH/tNCY4VnI0YbuVC7nzUoTBLgvacTLNCrTsvvjVuW3qvH/Ort4+GNvgNrAZiILG2+cA5EoXkVdZKuDw5MvowDd2QLlZFWeOO6B+hao7pTQwMmWMrqbFWzXt1t70ZW1Oz7ZBZt71sY6U8BP6Efdd2SDVGFiDMPoLrZ7hhobUqPpmnnaSzEU+9oTpNv2tM8qIyNQd3ik7EKiSzEY2cWk8jwWjDlBS8ub960z5LJwLkyZ4q7dsqiY2cdcLngU+m7NsR8ZkA4vBOEa91eKWeF/EOMj5tF1seRxFtSV0oOR9zuT/6fZBt0yMNWqic/Ehfh4oh8VHRMDs+0fnKZphpV6rd60Iim8QkNHrPoCyVMlbOiPZuFNVT2kzJQmLXIY/57wkJuDmW0HfvacqG1/2+vJpScFYLqK6cAljYO9ER9GVKEzHuKSFVm3tUdl7i752R1n/FrHa166IY4y7JGOxReaOHCHKbJhE0ET7oQdzzWLBdn6DK9beW7QL++wyOK759k1LN0nmPG3+L8IyYMgDQgOy5JWVljk+Qnhtx1yNxgSUkjTtcuGK2qnge91txNCL6k0hv4ngE8qj3C0HUK31fs86zmYCsWtkGcVASo5MxlCBhPQCwgSrA2TOPROgGwvFuLowF5AjRwX3ytdew4NeYCZ/fNTGIiNyBT46O3aLdy4x92Y2a92HDU8X9+k
  template:
    metadata:
      name: ghcr-creds
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
