---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAChWHlJCv31ewIPV4F1S/wl2FfC+Oc8twTdP/SXEfFg0N9ISWL9QghdCf8LMxPHxkxaoYUDkkjf4+js6B4xcTO4raJ66fLagAV0l2SHfgTUApVTg6FlnyOvQ3/fiGIipB/TXWaHAckv8i1vMG7eTnj8HZpTgeHBPvlFLjHIlN3P/g0OAPP6Y+4yS3+q40R0TOipOiNQUdPN9pK0VcSPYGApGiL3M4d7QsTy61J4vGFvL3FV5+KF1v3VH3RRDsIbdHRjx4LRfKUwuKPG80vI04NEcpLMcufS9V6rHWS0GxrvCGWpU6qMkik87lLkUG0Alo+Y8eQl36X9yj9M/4HULcoVjq8YxqjXM6zOYNpWXnaV4UxcsomksJ5rlQUSXI+mcSKPMB4XBcs/weLtinf5UWqqu/DoF7OrMl7A9zkttH4BLMHWud4V+BcVEc9Fu/l9tvMhLVx/r+iPGENeL243S9hIvmTZx6MQrBBHehrVpEit+sVDPrtTU9rEJ5j2GzC+gDQXjgOrDO7HQTeXdTFLbTEO/2DSIz2R0PrZ5/nDjtON6X/QYSQQrf+BBaE5zu6ctfCRv+lP4zoWPvikd2RwIAN6OVkz+UI6WPR3NA6Swp+chChTgFjYeoLy/3+t+56Q0/+JW1keQJgEY7IHKp/VKmmiRhAssVBbiTYNMHNXb6g9C+X1eV1LT3+e5zdX8tcKydQ01QF9/zQxfSj
    admin-user: AgAgLUMVrWLlVb3aRWZcLRrTkk7koAj5riU+PfasYG50OIfoq4WIb0SNXS2Zg8zCgA4N0G/M1j0pA2mmhbYjXBAIueO81lis3y0VpjbKgiGMEmVCco9GVlDzxJ3fbNGyRFmdLGzwDxEZd2S7anYYM26Z+82g0lxnpKeoHcrUFReqxVF6Htu36CJcdy/ZPo2dRHnoctmFqWO4IHP4j6UTgves7hfrHHokVPGIDzhlEAt2zxLfEbKgUoZFBtK7/eyZNyyGU1nOdlbWA3OyhU/i6VEtFWQRmwEUjSncGnFVIN+dvr9E2zIT5SxxmuvNJOXrLNq2QzhBvceBT/eukivkjJ+qvrnPJypqYwnTldkvmDU/pl3oxdO+UBrWaW1yzNeYl5GrW4Q0dEXjzHe48TBCaYnAEUPgkjw5/PSybK2bhymdHRgrxgHazdjhebDIF9m8GAXVGyg8Ma+fbpN20rKZoQn5wM4YYNTud5dfBunfxm/5AVMwVNSGpG88bKjjpbIcon4lUx848Sg1AihdKEvOZ+aUonWEO4hIuxRHyKlNJ29+YVE7t3HbO36eoavA5xL96/SWEpXcV561jRbkt/EnOMRzzNZwaPSXSHeiYqKT1XQxHwjcir/W5nePx/G9PvFtTR1uTXcZJ4vIEiMjyd+zrrj9ZPK55Od1nqjSuS1GRwcAK6cXT7XS5bz9HEC5WnTR51SV3T5aaSixqPE=
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
