apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kubernetes-ingress
    repo: https://haproxytech.github.io/helm-charts
    version: 1.45.1
    releaseName: kubernetes-ingress
    namespace: infra
    valuesInline:
      controller:
        kind: DaemonSet
        ingressClass: haproxy
        service:
          type: LoadBalancer