name: argocd-self
namespace: argocd
syncWave: "-10"

chart:
  repoURL: https://argoproj.github.io/argo-helm
  name: argo-cd
  version: 9.0.1

helmValues:
  configs:
    params:
      server.insecure: "true"

  server:
    ingress:
      enabled: true
      ingressClassName: haproxy
      hostname: argocd.lan