apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-haproxy
  source:
    repoURL: https://haproxytech.github.io/helm-charts
    chart: kubernetes-ingress
    targetRevision: "1.44.6"
    helm:
      valueFiles:
        - platform/haproxy/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
